[project]
name = "herbie-pdl"
version = "0.1.0"
description = "Convert Herbie patterns to pdl"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.0",
    "xdsl>=0.41.0",
]
